# Generated by Django 4.2.5 on 2023-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_calory", "0002_alter_products_product_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_measure",
            field=models.CharField(
                choices=[
                    ("piece", "piece"),
                    ("spoon", "spoon"),
                    ("gramm", "gramm"),
                    ("liter", "liter"),
                    ("cup", "cup"),
                ],
                max_length=25,
                verbose_name="Measure",
            ),
        ),
    ]
